[package]
name = "futures-signals-structs-derive"
version = "0.0.1"
edition = "2018"
autotests = false
publish = false

[lib]
proc-macro = true
futures-signals-structs = "../"

[dependencies]
quote = "1.0.7"
proc-macro2 = "1.0.19"

[dependencies.syn]
version = "1.0.39"
features = ["full"]
